export const resourceData = [
  {
    title: 'Schoolism',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://www.schoolism.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: 'website',
    reccommended: 'true',
    recCourses: {
      title: '',
      instructor: '',
    },
  },
  {
    title: 'New Masters Academy',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://nma.art',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: 'website',
    reccommended: 'true',
  },
  {
    title: 'Society of Visual Storytelling',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://www.svslearn.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: 'website',
  },
  {
    title: 'Will Weston',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: [
      'https://www.instagram.com/willwestonstudio',
      'https://www.twitch.tv/peterhanstyle',
    ],
    img: 'https://via.placeholder.com/400',
    cost: '',
    category: 'person',
    reccommended: 'true',
  },
  {
    title: 'Peter Han',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: [
      'https://www.instagram.com/peterhanstyle/',
      'https://www.twitch.tv/peterhanstyle',
    ],
    img: 'https://via.placeholder.com/400',
    cost: '',
    category: 'person',
    reccommended: 'true',
  },
  {
    title: 'Concept Design Academy',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'http://conceptdesignacad.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$750-800 per course',
    category: '',
  },
  {
    title: 'Draw a Box',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://drawabox.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: '',
  },
  {
    title: 'Modern Day James',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://drawabox.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: '',
  },
  {
    title: 'The Foundation Group',
    description: 'Lalalal lalalal lalalal alalalal alalalala',
    url: 'https://drawabox.com/',
    img: 'https://via.placeholder.com/400',
    cost: '$25 Monthly',
    category: '',
  },
]
